# Base image
FROM elek/flume

ARG FLUME_HOME=/opt/flume
ARG PLUGINS_DIR=${FLUME_HOME}/plugins.d
ARG PLUGIN_NAME=flume-ftp

# ADD new config file
ADD ./conf/flume.conf /opt/flume/conf/flume-conf.properties

# SFTP plugin libs
ADD ./lib/jsch-0.1.54.jar ${PLUGINS_DIR}/${PLUGIN_NAME}/libext/
ADD ./lib/commons-net-3.3.jar ${PLUGINS_DIR}/${PLUGIN_NAME}/libext/
ADD ./lib/flume-ftp-source-2.2.0.jar ${PLUGINS_DIR}/${PLUGIN_NAME}/lib/

# Flume tmp dir
RUN mkdir /var/log/flume-ftp