FROM python:3.9

# Create tmp dir
RUN mkdir -p /tmp/sftp_cache;

# set the working directory in the container
WORKDIR /eventgen

# copy the dependencies file to the working directory
COPY resources/ /eventgen/resources

# install dependencies
RUN pip install -r /eventgen/resources/requirements.txt

# copy the content of the local src directory to the working directory
COPY src/ /eventgen/app

# Run event generator
ENTRYPOINT [ "bash", "/eventgen/app/run.sh"]
